# Generated by Django 3.0.7 on 2020-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstusermodel',
            name='count',
            field=models.IntegerField(choices=[('Предложения', '1'), ('Предложения', '2'), ('Предложения', '3'), ('Предложения', '4')]),
        ),
        migrations.AlterField(
            model_name='firstusermodel',
            name='order',
            field=models.CharField(choices=[('Предложения', '1'), ('Предложения', '2'), ('Предложения', '3'), ('Предложения', '4')], max_length=32, verbose_name='order'),
        ),
    ]
