# Generated by Django 3.0.7 on 2020-12-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201231_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstusermodel',
            name='count',
        ),
    ]
